#!/bin/bash
#PBS -l nodes=1:ppn=1:gpus=1
#PBS -l walltime=01:00:00
#PBS -A sme-610-aa
#PBS -V
cd /home/yiulau/ift6266/development
echo ${MYVAR[*]} > debugoutput1

if [ "x" == "x$MYVAR" ] ; then
    echo "Variable is not set" > debugoutput
else
    echo "Variable says: ${MYVAR[*]}" >debugoutput
fi

