# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IFT 6266 Winter 2016
email: yiu.lau@mail.mcgill.ca
description: > # this means to ignore newlines until "baseurl:"
  This is my course blog for IFT 6266 at U de M in the winter semester of 2016.
baseurl: "/ift6266" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username: yiulau 

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable Github Flavoured Markdown (fenced code blocks)
exclude : [vendor]
